import React, { useEffect, useState } from 'react';
import { Link, NavLink, Outlet, useParams } from 'react-router-dom';
import { ArrowUpRight, CalendarDays, CheckCircle2, Globe2, Menu, Play, ShieldCheck, Trophy, Users, X } from 'lucide-react';
import { friendlyError, TERMS_VERSION, useCommunity } from './CommunityContext';
import { legalDocuments, legalReady, operator } from './legal';
import type { CommunityProfile } from './types';
import './community.css';

export function CommunityLayout() {
  const { profile, mode, error, isAdmin } = useCommunity();
  const [menu, setMenu] = useState(false);
  return <div className="c-app"><header className="c-header">
    <Link className="c-brand" to="/" aria-label="Cantera, inicio">cantera<span>●</span></Link>
    <button className="c-menu" onClick={() => setMenu(!menu)} aria-expanded={menu} aria-label="Abrir navegación">{menu ? <X /> : <Menu />}</button>
    <nav aria-label="Navegación principal" className={menu ? 'c-nav open' : 'c-nav'} onClick={() => setMenu(false)}><NavLink to="/" end>Inicio</NavLink><NavLink to="/play">Juega</NavLink><NavLink to="/feed">Comunidad</NavLink>{isAdmin ? <NavLink to="/admin">Administración</NavLink> : null}</nav>
    <Link to="/profile" className="c-account">{profile ? <><span className="c-avatar">{profile.name.slice(0, 1).toUpperCase()}</span><span>{profile.name.split(' ')[0]}</span></> : <>Únete gratis <ArrowUpRight size={17} /></>}</Link>
  </header>{mode === 'demo' ? <div className="c-demo" role="status">Entorno de prueba local · tus cambios se guardan sólo en este navegador. <Link to="/profile">Entrar con una cuenta real</Link></div> : null}
    {error ? <div className="c-global-error" role="alert">{error} <Link to="/profile">Revisar cuenta</Link></div> : null}
    <main className="c-main"><Outlet /></main><footer className="c-footer"><div><Link className="c-brand" to="/">cantera<span>●</span></Link><p>El fútbol nos reúne. En cualquier lugar.</p></div>
      <nav aria-label="Información"><Link to="/about">Misión y patrocinio</Link><Link to="/legal/terms">Términos</Link><Link to="/legal/privacy">Privacidad</Link><Link to="/legal/cookies">Cookies y almacenamiento</Link></nav><span>Acceso gratuito · sin seguimiento publicitario</span></footer></div>;
}
export function CommunityHome() {
  const { events, profile } = useCommunity();
  const upcoming = events.filter(e => e.status === 'open' && Date.parse(e.startAt) > Date.now()).sort((a, b) => Date.parse(a.startAt) - Date.parse(b.startAt)).slice(0, 3);
  return <><section className="c-hero"><div className="c-hero-copy"><p className="c-eyebrow"><span className="c-dot" /> UNA COMUNIDAD. TODO EL FÚTBOL.</p>
    <h1>Del barrio<br />al <em>mundo.</em></h1><p className="c-lead">Organiza tu próximo partido. Crea un torneo. Comparte lo que te hace sentir el fútbol.</p>
    <div className="c-actions"><Link className="c-button" to="/play">Encuentra tu partido <ArrowUpRight size={18} /></Link><Link className="c-button secondary" to={profile ? '/play?create=1' : '/profile'}>Organiza gratis</Link></div>
    <div className="c-hero-note"><Globe2 size={17} /> Amateurs, profesionales, equipos y grupos. Todos tienen sitio.</div>
  </div><div className="c-field-card"><div className="c-field-meta"><span>EL PUNTO DE ENCUENTRO</span><span>01 / ∞</span></div>
    <svg viewBox="0 0 340 390" role="img" aria-label="Campo de fútbol y su comunidad"><rect x="40" y="45" width="260" height="300" rx="2" /><path d="M40 195H300 M120 45V95H220V45 M120 345V295H220V345 M144 45V64H196V45 M144 345V326H196V345" /><circle cx="170" cy="195" r="42" /><circle className="c-player-dot" cx="105" cy="150" r="12" /><circle className="c-player-dot lime" cx="238" cy="220" r="12" /><circle className="c-player-dot" cx="125" cy="278" r="12" /><circle className="c-player-dot lime" cx="205" cy="106" r="12" /><path className="c-pass" d="M105 150 Q180 120 238 220 Q185 266 125 278" /></svg>
    <div className="c-field-caption"><span>La próxima historia<br /><strong>se juega contigo.</strong></span><span className="c-field-mark">C.</span></div>
  </div></section><section className="c-section"><div className="c-section-head"><div><p className="c-eyebrow">ENCUENTRA TU GENTE</p><h2>Un balón. Muchas posibilidades.</h2></div><Link to="/play">Explorar encuentros <ArrowUpRight size={17} /></Link></div>
    <div className="c-pillar-grid"><Link to="/play?type=match" className="c-pillar"><CalendarDays /><span>01</span><h3>Quedamos para jugar</h3><p>Partidos por país, ciudad y nivel. Apúntate o reúne a tu propio grupo.</p><ArrowUpRight /></Link><Link to="/play?type=tournament" className="c-pillar"><Trophy /><span>02</span><h3>Algo más que un partido</h3><p>Torneos con inscripciones, calendario, resultados y clasificación.</p><ArrowUpRight /></Link><Link to="/feed" className="c-pillar"><Play /><span>03</span><h3>Tu fútbol tiene historia</h3><p>Reels, fotografías y logros. Comparte el camino, además del resultado.</p><ArrowUpRight /></Link></div>
  </section><section className="c-section"><div className="c-section-head"><div><p className="c-eyebrow">EL PRÓXIMO ENCUENTRO</p><h2>Nos vemos en el campo.</h2></div><Link to="/play">Ver todos <ArrowUpRight size={17} /></Link></div>
    {upcoming.length ? <div className="c-upcoming">{upcoming.map(e => <Link to={`/play/${e.id}`} className="c-upcoming-card" key={e.id}><span className="c-eyebrow">{e.type === 'match' ? 'PARTIDO' : 'TORNEO'} · F{e.format}</span><h3>{e.title}</h3><p>{e.city}, {e.country}</p><time dateTime={e.startAt}>{new Intl.DateTimeFormat('es', { timeZone: e.timeZone, dateStyle: 'medium', timeStyle: 'short' }).format(new Date(e.startAt))}</time><span className="c-event-spaces">{e.capacity - Object.keys(e.participants).length} plazas disponibles <ArrowUpRight size={17} /></span></Link>)}</div> : <div className="c-invitation"><Users size={35} /><div><h3>Todo empieza con alguien que propone jugar.</h3><p>Crea el primer encuentro y comparte la invitación con tu equipo.</p></div><Link to={profile ? '/play?create=1' : '/profile'} className="c-button">Crear un encuentro</Link></div>}
  </section><section className="c-mission"><p className="c-eyebrow">GRATIS POR CONVICCIÓN</p><h2>El talento no debería<br />depender de una cuota.</h2><p>Cantera nace como una iniciativa sin ánimo de lucro que busca patrocinadores y aliados para acercar el fútbol a más personas.</p><Link to="/about">Conoce la misión <ArrowUpRight size={18} /></Link></section></>;
}
export function ProfilePage() {
  const api = useCommunity(); const { profile, mode, isAdmin } = api;
  const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const [draft, setDraft] = useState<CommunityProfile | null>(null); const [accepted, setAccepted] = useState(false);
  const [organization, setOrganization] = useState(''); const [evidence, setEvidence] = useState('');
  useEffect(() => { setDraft(profile); setAccepted(profile?.acceptedTermsVersion === TERMS_VERSION); }, [profile]);
  async function action(work: () => Promise<void>, message = '') { setBusy(true); setError(''); setSuccess(''); try { await work(); setSuccess(message); } catch (err) { setError(friendlyError(err)); } finally { setBusy(false); } }
  const pending = api.verificationRequests.find(r => r.userId === profile?.id);
  if (!profile || !draft) return <section className="c-profile-intro"><div><p className="c-eyebrow">TU SITIO EN CANTERA</p><h1>Juega. Comparte.<br />Forma parte.</h1><p className="c-lead">Una cuenta para crear encuentros, inscribirte con tu equipo y contar tu historia. Sin cuotas.</p><p>Esta primera versión de cuentas está dirigida a mayores de 18 años. El acceso con tutores para menores forma parte del plan de expansión.</p></div>
    <div className="c-panel c-login"><h2>Únete a la comunidad</h2><p>Elige tu nombre público después de entrar.</p><button disabled={busy} className="c-button" onClick={() => action(api.login)}>Continuar con Google <ArrowUpRight size={17} /></button><p className="c-small">Al acceder podrás consultar los <Link to="/legal/terms">términos</Link> y la <Link to="/legal/privacy">privacidad</Link> antes de completar tu cuenta.</p>
      {api.demoEnabled ? <details><summary>Probar en este dispositivo</summary><p className="c-small">Entorno aislado para comprobar funciones. No publica en la comunidad.</p><label>Tu nombre<input className="c-input" value={name} onChange={e => setName(e.target.value)} maxLength={100} placeholder="Tu nombre o grupo" /></label><button disabled={busy || !name.trim()} className="c-button secondary" onClick={() => action(() => api.beginDemo(name))}>Abrir entorno de prueba</button></details> : null}{error ? <p className="c-error" role="alert">{error}</p> : null}
    </div></section>;
  const update = <K extends keyof CommunityProfile>(key: K, value: CommunityProfile[K]) => setDraft({ ...draft, [key]: value });
  return <section className="c-section c-profile"><div className="c-section-head"><div><p className="c-eyebrow">TU IDENTIDAD DEPORTIVA</p><h1>Tu perfil</h1></div><div className="c-actions">{mode === 'demo' ? <button className="c-button" disabled={busy} onClick={() => action(api.login)}>Entrar con Google</button> : null}<button className="c-button secondary" disabled={busy} onClick={() => action(api.signOut)}>Cerrar sesión</button></div></div>
    <div className="c-profile-grid"><form className="c-panel" onSubmit={e => { e.preventDefault(); void action(async () => {
      if (mode === 'cloud' && !legalReady) throw new Error('El responsable debe completar los datos legales del servicio antes de abrir el registro.');
      const { id, verification, createdAt, ...input } = draft;
      await api.saveProfile({ ...input, acceptedTermsVersion: accepted ? TERMS_VERSION : '', acceptedTermsAt: profile.acceptedTermsVersion === TERMS_VERSION ? profile.acceptedTermsAt : new Date().toISOString() });
    }, 'Perfil guardado. Ya puedes organizar y participar.'); }}>
      <div className="c-form-grid"><label>Nombre público<input className="c-input" value={draft.name} onChange={e => update('name', e.target.value)} maxLength={100} required /></label><label>Tipo de cuenta<select className="c-input" value={draft.entityType} onChange={e => update('entityType', e.target.value as CommunityProfile['entityType'])}><option value="individual">Persona</option><option value="group">Grupo</option><option value="club">Club o entidad</option></select></label>
      <label>País<input className="c-input" value={draft.country} onChange={e => update('country', e.target.value)} maxLength={100} required /></label><label>Ciudad<input className="c-input" value={draft.city} onChange={e => update('city', e.target.value)} maxLength={100} required /></label><label>Equipo o grupo<input className="c-input" value={draft.team} onChange={e => update('team', e.target.value)} maxLength={100} /></label><label>Posición o función<input className="c-input" value={draft.position} onChange={e => update('position', e.target.value)} maxLength={100} /></label><label>Nivel<select className="c-input" value={draft.level} onChange={e => update('level', e.target.value as CommunityProfile['level'])}><option value="amateur">Amateur</option><option value="professional">Profesional</option></select></label></div>
      <label>Tu historia<textarea className="c-input" value={draft.bio} onChange={e => update('bio', e.target.value)} maxLength={1000} rows={4} /></label>
      <label className="c-check"><input type="checkbox" checked={draft.adultConfirmed} onChange={e => update('adultConfirmed', e.target.checked)} required />Soy mayor de 18 años y, si represento a una entidad, tengo autorización para hacerlo.</label><label className="c-check"><input type="checkbox" checked={accepted} onChange={e => setAccepted(e.target.checked)} required /><span>Acepto los <Link to="/legal/terms">términos de uso</Link> y he leído la <Link to="/legal/privacy">privacidad</Link>. Versión {TERMS_VERSION}.</span></label>
      <p className="c-small">Tu perfil, tus publicaciones y los nombres de inscripción son públicos. No incluyas datos privados.</p><button disabled={busy} className="c-button" type="submit">{busy ? 'Guardando…' : 'Guardar perfil'}</button>
    </form><aside className="c-panel c-verify"><ShieldCheck size={32} /><h2>{profile.verification === 'verified' ? 'Cuenta verificada' : 'El reconocimiento se comprueba.'}</h2><p>Personas, grupos y clubes pueden pedir una verificación voluntaria. El administrador revisa cada solicitud. Nunca depende de pagar.</p>
      {profile.verification === 'verified' ? <p className="c-success"><CheckCircle2 size={18} /> Identidad revisada por el administrador.</p> : <form onSubmit={e => { e.preventDefault(); void action(() => api.requestVerification(organization, evidence), mode === 'demo' ? 'Solicitud guardada en el entorno local de prueba.' : 'Solicitud enviada al administrador.'); }}>
        {pending ? <p className="c-small">Estado: {pending.status === 'pending' ? 'pendiente de revisión' : pending.status === 'rejected' ? 'no aprobada; puedes enviar más información' : 'aprobada'}</p> : null}<label>Persona o entidad a verificar<input className="c-input" value={organization} onChange={e => setOrganization(e.target.value)} maxLength={100} required /></label><label>Información y enlaces para comprobarla<textarea className="c-input" value={evidence} onChange={e => setEvidence(e.target.value)} rows={4} maxLength={2000} required placeholder="Web oficial, perfil público o información de representación" /></label><p className="c-small">Sólo tú y el administrador podéis leer esta solicitud. No envíes documentos de identidad.</p><button className="c-button secondary" disabled={busy || pending?.status === 'pending'}>Solicitar verificación</button>
      </form>}{operator.email ? <a className="c-contact" href={`mailto:${operator.email}`}>Contactar con el administrador</a> : null}{isAdmin ? <Link className="c-button secondary" to="/admin">Abrir administración</Link> : null}
    </aside></div>{error ? <p className="c-error" role="alert">{error}</p> : null}{success ? <p className="c-success" role="status">{success}</p> : null}
    <div className="c-section-head"><h2>Tu actividad</h2><span>{api.events.filter(e => e.ownerId === profile.id).length} encuentros · {api.posts.filter(p => p.authorId === profile.id).length} publicaciones</span></div><div className="c-upcoming">{api.events.filter(e => e.ownerId === profile.id || e.participants[profile.id]).map(e => <Link key={e.id} className="c-upcoming-card" to={`/play/${e.id}`}><h3>{e.title}</h3><p>{e.city}, {e.country}</p><span>{e.ownerId === profile.id ? 'Organizas este encuentro' : 'Estás inscrito'}</span></Link>)}</div>
  </section>;
}
export function LegalPage() {
  const { kind } = useParams(); const page = legalDocuments[kind as keyof typeof legalDocuments];
  if (!page) return <div className="c-empty">Documento no encontrado. <Link to="/">Volver</Link></div>;
  return <article className="c-legal c-section"><p className="c-eyebrow">TRANSPARENCIA · VERSIÓN {TERMS_VERSION}</p><h1>{page.title}</h1><p className="c-lead">{page.intro}</p><div className="c-panel c-operator"><strong>Responsable: {operator.name || 'pendiente de identificación'}</strong><p>País de operación: {operator.country || 'pendiente'}</p><p>Contacto: {operator.email ? <a href={`mailto:${operator.email}`}>{operator.email}</a> : 'pendiente de configurar'}</p>{!legalReady ? <p className="c-error">Documento en preparación. El registro en la comunidad requiere completar la identificación del responsable.</p> : null}</div>
    {page.sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}<p className="c-small">Proveedores: <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noreferrer">Firebase</a> · <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noreferrer">Vercel</a>.</p></article>;
}
export function AboutPage() {
  return <article className="c-section c-legal"><p className="c-eyebrow">FÚTBOL COMO PUNTO DE ENCUENTRO</p><h1>Una cancha<br />sin fronteras.</h1><p className="c-lead">Cantera busca que organizarse, jugar y mostrar el propio recorrido deportivo sea accesible para todos.</p><section><h2>Una iniciativa con propósito</h2><p>El proyecto nace con vocación sin ánimo de lucro. Su núcleo gratuito permite organizar encuentros, compartir contenido y desarrollar una identidad deportiva, desde un grupo de amigos hasta un club profesional. Esta vocación no implica que exista ya una asociación registrada o una acreditación benéfica.</p></section><section><h2>Patrocinio que abre oportunidades</h2><p>Buscamos aliados que financien infraestructura, comunidad y acceso al deporte. Los acuerdos deberán identificar al patrocinador, sus aportaciones y el uso de los recursos. La verificación y las decisiones de moderación mantendrán su independencia.</p></section><section><h2>Una expansión trazable</h2><p>La hoja de ruta parte de encuentros y contenido, sigue con herramientas para organizadores y tutela de menores, y avanza hacia alianzas locales. El whitepaper y el plan del proyecto documentan los objetivos, los hitos y los criterios de lanzamiento.</p><div className="c-actions"><a className="c-button secondary" href={`${import.meta.env.BASE_URL}Cantera-Whitepaper.pdf`} download="Cantera-Whitepaper.pdf">Descargar whitepaper PDF <ArrowUpRight size={18} /></a><a href={`${import.meta.env.BASE_URL}whitepaper.md`} download="Cantera-Whitepaper.md">Texto editable</a></div></section>{operator.email ? <a className="c-button" href={`mailto:${operator.email}?subject=Colaborar%20con%20Cantera`}>Proponer una colaboración <ArrowUpRight size={18} /></a> : <p className="c-small">El contacto de colaboraciones se publicará cuando el responsable complete sus datos.</p>}</article>;
}
export function AdminPage() {
  const api = useCommunity(); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const run = async (id: string, work: () => Promise<void>) => { setBusy(id); setError(''); try { await work(); } catch (err) { setError(friendlyError(err)); } finally { setBusy(''); } };
  if (!api.isAdmin) return <div className="c-empty"><ShieldCheck /><h1>Administración</h1><p>Esta sección está reservada al responsable de Cantera.</p><Link to="/profile" className="c-button">Revisar cuenta</Link></div>;
  return <section className="c-section"><p className="c-eyebrow">CONTROL DE LA COMUNIDAD</p><h1>Administración</h1>{error ? <p role="alert" className="c-error">{error}</p> : null}<h2>Solicitudes de verificación</h2>{api.verificationRequests.filter(r => r.status === 'pending').length === 0 ? <p>No hay solicitudes pendientes.</p> : api.verificationRequests.filter(r => r.status === 'pending').map(r => <article className="c-panel c-admin-card" key={r.id}><h3>{r.organization}</h3><p>Solicitante: {r.name}</p><p className="c-prewrap">{r.evidence}</p><div className="c-actions"><button className="c-button" disabled={Boolean(busy)} onClick={() => run(r.id, () => api.reviewVerification(r.id, true))}>Aprobar</button><button className="c-button secondary" disabled={Boolean(busy)} onClick={() => run(r.id, () => api.reviewVerification(r.id, false))}>No aprobar</button></div></article>)}
    <h2>Denuncias</h2>{api.reports.filter(r => r.status === 'open').length === 0 ? <p>No hay denuncias abiertas.</p> : api.reports.filter(r => r.status === 'open').map(r => <article className="c-panel c-admin-card" key={r.id}><p>{r.reason}</p><Link to={`/feed?post=${r.postId}`}>Revisar publicación</Link><div className="c-actions"><button className="c-button secondary" disabled={Boolean(busy)} onClick={() => run(r.id, () => api.resolveReport(r.id, false))}>Cerrar sin retirar</button><button className="c-button" disabled={Boolean(busy)} onClick={() => { if (window.confirm('¿Retirar la publicación denunciada? Esta acción elimina el contenido.')) void run(r.id, () => api.resolveReport(r.id, true)); }}>Retirar publicación</button></div></article>)}
  </section>;
}
