import React, { Suspense, useEffect, useRef, useState } from 'react';
import { Link, NavLink, Outlet, useLocation, useParams } from 'react-router-dom';
import { ArrowUpRight, Bell, CalendarDays, CheckCircle2, Globe2, House, Image, Play, Plus, Search, ShieldCheck, Trophy, UserRound, Users, X } from 'lucide-react';
import { friendlyError, TERMS_VERSION, useCommunity } from './CommunityContext';
import { hostingProvider, legalDocuments, legalReady, operator } from './legal';
import { AppAvailability } from './AppAvailability';
import { MobileHome } from './MobileHome';
import { isPublicEvent } from './eventPrivacy';
import '@fontsource-variable/manrope';
import './community.css';
import './mobile.css';
import './brand.css';

const routeNames: Record<string, string> = {
  '/': 'Inicio', '/play': 'Juega', '/feed': 'Comunidad', '/profile': 'Tu perfil',
  '/messages': 'Mensajes privados', '/connect': 'Conexiones e invitaciones', '/teams': 'Equipos y grupos', '/activity': 'Actividad', '/about': 'Misión y patrocinio', '/admin': 'Administración', '/people': 'Personas y equipos',
  '/legal/terms': 'Términos de uso', '/legal/privacy': 'Privacidad', '/legal/cookies': 'Cookies y almacenamiento',
};

export function CommunityLayout() {
  const { profile, mode, error, isAdmin, mediaUploadsEnabled, eventNotices, runtimeConfig } = useCommunity();
  const { pathname, search } = useLocation();
  const mainRef = useRef<HTMLElement>(null);
  const previousPath = useRef(pathname);
  const [createOpen, setCreateOpen] = useState(false);
  const createDialog = useRef<HTMLDialogElement>(null);
  const routeName = routeNames[pathname] || (pathname.startsWith('/messages/') ? 'Conversación privada' : pathname.startsWith('/invite/') ? 'Aceptar invitación' : pathname.startsWith('/play/') ? 'Detalle del encuentro' : pathname.startsWith('/teams/') ? 'Equipo' : pathname.startsWith('/people/') ? 'Perfil de la comunidad' : 'LaCantera');
  useEffect(() => {
    const changed = previousPath.current !== pathname;
    previousPath.current = pathname;
    if (!changed) return;
    window.scrollTo({ top: 0, left: 0 });
    if (new URLSearchParams(search).has('create')) return;
    const frame = requestAnimationFrame(() => {
      if (!document.querySelector('dialog[open]')) mainRef.current?.focus({ preventScroll: true });
    });
    return () => cancelAnimationFrame(frame);
  }, [pathname, search]);
  useEffect(() => {
    const dialog = createDialog.current;
    if (!dialog) return;
    if (createOpen && !dialog.open) dialog.showModal();
    if (!createOpen && dialog.open) dialog.close();
  }, [createOpen]);
  const createLink = (destination: string) => profile ? destination : `/profile?returnTo=${encodeURIComponent(destination)}`;
  return <div className="c-app"><header className="c-header">
    <Link className="c-brand" to="/" aria-label="LaCantera, inicio">LaCantera<span>●</span></Link>
    <nav aria-label="Navegación principal" className="c-nav"><NavLink to="/" end>Inicio</NavLink><NavLink to="/play">Juega</NavLink><NavLink to="/feed">Comunidad</NavLink><NavLink to="/teams">Equipos</NavLink><NavLink to="/messages">Mensajes</NavLink><NavLink to="/connect">Conexiones</NavLink>{isAdmin ? <NavLink to="/admin">Administración</NavLink> : null}</nav>
    <div className="c-header-tools">{profile ? <Link to="/activity" className="c-discover-link c-notice-bell" aria-label={`Actividad${eventNotices.some(n => !n.readAt) ? ", hay avisos sin leer" : ""}`}><Bell size={21} aria-hidden="true" />{eventNotices.some(n => !n.readAt) ? <span /> : null}</Link> : null}<Link to="/people" className="c-discover-link" aria-label="Buscar personas y clubes"><Search size={21} aria-hidden="true" /></Link><Link to="/profile" className="c-account" aria-label={profile ? 'Tu perfil' : 'Entrar a LaCantera'}>{profile ? <><span className="c-avatar">{profile.name.slice(0, 1).toUpperCase()}</span><span className="c-account-label">{profile.name.split(' ')[0]}</span></> : <><span className="c-account-label">Únete gratis <ArrowUpRight size={17} /></span><UserRound className="c-mobile-account-icon" size={20} /></>}</Link></div>
  </header><AppAvailability />{import.meta.env.DEV && import.meta.env.VITE_FIREBASE_EMULATORS === 'true' ? <div className="c-demo" role="status">Pruebas Firebase locales · ninguna acción se publica en producción.</div> : null}{mode === 'demo' ? <div className="c-demo" role="status"><span className="c-desktop-only">Entorno de prueba local · tus cambios se guardan sólo en este navegador.</span><span className="c-mobile-only">Prueba local · sólo en este dispositivo.</span> <Link to="/profile">Cuenta real</Link></div> : null}
    {mode === 'cloud' && runtimeConfig.serviceStatus !== 'open' ? <div className="c-service-status" role="status">{runtimeConfig.serviceStatus === 'paused' ? 'Comunidad en mantenimiento.' : 'Estamos preparando la apertura de LaCantera.'} <Link to="/about">Conoce el proyecto</Link></div> : null}{error ? <div className="c-global-error" role="alert">{error} <Link to="/profile">Revisar cuenta</Link></div> : null}
    <div className="c-route-announcement" role="status" aria-live="polite" aria-atomic="true">{routeName}</div>
    <main ref={mainRef} className="c-main" tabIndex={-1}><Suspense fallback={<div className="c-app-loading" role="status">Cargando…</div>}><Outlet /></Suspense></main><footer className="c-footer"><div><Link className="c-brand" to="/">LaCantera<span>●</span></Link><p>El fútbol nos reúne. En cualquier lugar.</p></div>
      <nav aria-label="Información"><Link to="/about">Misión y patrocinio</Link><Link to="/legal/terms">Términos</Link><Link to="/legal/privacy">Privacidad</Link><Link to="/legal/cookies">Cookies y almacenamiento</Link></nav><span>Acceso gratuito · sin seguimiento publicitario</span></footer>
    <details className="c-mobile-info"><summary>Sobre LaCantera y privacidad</summary><nav aria-label="Información de LaCantera"><Link to="/connect">Conexiones e invitaciones</Link><Link to="/messages">Mensajes privados</Link><Link to="/people">Personas y clubes</Link><Link to="/teams">Equipos y grupos</Link><Link to="/activity">Actividad</Link><Link to="/about">Misión y patrocinio</Link><Link to="/legal/terms">Términos de uso</Link><Link to="/legal/privacy">Privacidad</Link><Link to="/legal/cookies">Cookies y almacenamiento</Link>{isAdmin ? <Link to="/admin">Administración</Link> : null}</nav></details>
    <nav className="c-bottom-nav" aria-label="Navegación móvil">
      <NavLink to="/" end><House size={22} aria-hidden="true" /><span>Inicio</span></NavLink>
      <NavLink to="/play"><CalendarDays size={22} aria-hidden="true" /><span>Juega</span></NavLink>
      <button className="c-bottom-create" aria-label="Crear" aria-haspopup="dialog" aria-expanded={createOpen} onClick={() => setCreateOpen(true)}><span className="c-create-icon"><Plus size={25} aria-hidden="true" /></span><span>Crear</span></button>
      <NavLink to="/feed" className={({ isActive }) => isActive || pathname.startsWith('/people') ? 'active' : ''}><Users size={22} aria-hidden="true" /><span>Comunidad</span></NavLink>
      <NavLink to="/profile"><UserRound size={22} aria-hidden="true" /><span>Perfil</span></NavLink>
    </nav>
    <dialog ref={createDialog} className="c-create-sheet" aria-labelledby="c-create-title" onCancel={() => setCreateOpen(false)} onClose={() => setCreateOpen(false)}>
      <div className="c-sheet-handle" aria-hidden="true" /><header><div><p>COMPARTE TU FÚTBOL</p><h2 id="c-create-title">¿Qué quieres crear?</h2></div><button className="c-sheet-close" aria-label="Cerrar opciones de creación" onClick={() => setCreateOpen(false)}><X size={22} /></button></header>
      {!profile ? <p className="c-sheet-note">Entra con tu cuenta para organizar o publicar.</p> : null}
      <div className="c-create-options" onClick={() => setCreateOpen(false)}>
        <Link to={createLink('/teams?create=1')}><span><Users size={22} /></span><div><strong>Un equipo o grupo</strong><small>Miembros, responsables e invitaciones.</small></div><ArrowUpRight size={18} /></Link><Link to={createLink('/play?create=1&type=match')}><span><CalendarDays size={22} /></span><div><strong>Un partido</strong><small>Reúne a tu gente para jugar.</small></div><ArrowUpRight size={18} /></Link>
        <Link to={createLink('/play?create=1&type=tournament')}><span><Trophy size={22} /></span><div><strong>Un torneo</strong><small>Organiza una liga o una copa.</small></div><ArrowUpRight size={18} /></Link>
        <Link to={createLink('/feed?create=achievement')}><span><CheckCircle2 size={22} /></span><div><strong>Un logro</strong><small>Cuenta lo que has conseguido.</small></div><ArrowUpRight size={18} /></Link>
        {mediaUploadsEnabled ? <><Link to={createLink('/feed?create=photo')}><span><Image size={22} /></span><div><strong>Una foto</strong><small>Comparte un momento de la cancha.</small></div><ArrowUpRight size={18} /></Link><Link to={createLink('/feed?create=reel')}><span><Play size={22} /></span><div><strong>Un reel</strong><small>Tu fútbol en movimiento.</small></div><ArrowUpRight size={18} /></Link></> : <p className="c-sheet-note">Fotos y reels pendientes del patrocinio del almacenamiento.</p>}
      </div>
    </dialog>
  </div>;
}
export function CommunityHome() {
  const { events, profile } = useCommunity();
  if (profile) return <div className="c-signed-home"><MobileHome /></div>;
  const upcoming = events.filter(e => isPublicEvent(e) && e.status === 'open' && Date.parse(e.startAt) > Date.now()).sort((a, b) => Date.parse(a.startAt) - Date.parse(b.startAt)).slice(0, 3);
  return <><MobileHome /><div className="c-desktop-home"><section className="c-hero"><div className="c-hero-copy"><p className="c-eyebrow"><span className="c-dot" /> UNA COMUNIDAD. TODO EL FÚTBOL.</p>
    <h1>Del barrio<br />al <em>mundo.</em></h1><p className="c-lead">Organiza tu próximo partido. Crea un torneo. Comparte lo que te hace sentir el fútbol.</p>
    <div className="c-actions"><Link className="c-button" to="/play">Encuentra tu partido <ArrowUpRight size={18} /></Link><Link className="c-button secondary" to={profile ? '/play?create=1' : '/profile'}>Organiza gratis</Link></div>
    <div className="c-hero-note"><Globe2 size={17} /> Amateurs, profesionales, equipos y grupos. Primera versión para mayores de 18 años.</div>
  </div><div className="c-field-card"><div className="c-field-meta"><span>EL PUNTO DE ENCUENTRO</span><span>01 / ∞</span></div>
    <svg viewBox="0 0 340 390" role="img" aria-label="Campo de fútbol y su comunidad"><rect x="40" y="45" width="260" height="300" rx="2" /><path d="M40 195H300 M120 45V95H220V45 M120 345V295H220V345 M144 45V64H196V45 M144 345V326H196V345" /><circle cx="170" cy="195" r="42" /><circle className="c-player-dot" cx="105" cy="150" r="12" /><circle className="c-player-dot lime" cx="238" cy="220" r="12" /><circle className="c-player-dot" cx="125" cy="278" r="12" /><circle className="c-player-dot lime" cx="205" cy="106" r="12" /><path className="c-pass" d="M105 150 Q180 120 238 220 Q185 266 125 278" /></svg>
    <div className="c-field-caption"><span>La próxima historia<br /><strong>se juega contigo.</strong></span><span className="c-field-mark">C.</span></div>
  </div></section><section className="c-section"><div className="c-section-head"><div><p className="c-eyebrow">ENCUENTRA TU GENTE</p><h2>Un balón. Muchas posibilidades.</h2></div><Link to="/play">Explorar encuentros <ArrowUpRight size={17} /></Link></div>
    <div className="c-pillar-grid"><Link to="/play?type=match" className="c-pillar"><CalendarDays /><span>01</span><h3>Quedamos para jugar</h3><p>Partidos por país, ciudad y nivel. Apúntate o reúne a tu propio grupo.</p><ArrowUpRight /></Link><Link to="/play?type=tournament" className="c-pillar"><Trophy /><span>02</span><h3>Algo más que un partido</h3><p>Torneos con inscripciones, calendario, resultados y clasificación.</p><ArrowUpRight /></Link><Link to="/feed" className="c-pillar"><Play /><span>03</span><h3>Tu fútbol tiene historia</h3><p>Comparte tus logros escritos y el camino que recorres. Fotos y reels pendientes de patrocinio.</p><ArrowUpRight /></Link></div>
  </section><section className="c-section"><div className="c-section-head"><div><p className="c-eyebrow">EL PRÓXIMO ENCUENTRO</p><h2>Nos vemos en el campo.</h2></div><Link to="/play">Ver todos <ArrowUpRight size={17} /></Link></div>
    {upcoming.length ? <div className="c-upcoming">{upcoming.map(e => <Link to={`/play/${e.id}`} className="c-upcoming-card" key={e.id}><span className="c-eyebrow">{e.type === 'match' ? 'PARTIDO' : 'TORNEO'} · F{e.format}</span><h3>{e.title}</h3><p>{e.city}, {e.country}</p><time dateTime={e.startAt}>{new Intl.DateTimeFormat('es', { timeZone: e.timeZone, dateStyle: 'medium', timeStyle: 'short' }).format(new Date(e.startAt))}</time><span className="c-event-spaces">{e.capacity - Object.keys(e.participants).length} plazas disponibles <ArrowUpRight size={17} /></span></Link>)}</div> : <div className="c-invitation"><Users size={35} /><div><h3>Todo empieza con alguien que propone jugar.</h3><p>Crea el primer encuentro y comparte la invitación con tu equipo.</p></div><Link to={profile ? '/play?create=1' : '/profile'} className="c-button">Crear un encuentro</Link></div>}
  </section><section className="c-mission"><p className="c-eyebrow">GRATIS POR CONVICCIÓN</p><h2>El talento no debería<br />depender de una cuota.</h2><p>LaCantera nace como una iniciativa sin ánimo de lucro que busca patrocinadores y aliados para acercar el fútbol a más personas.</p><Link to="/about">Conoce la misión <ArrowUpRight size={18} /></Link></section></div></>;
}
export { ProfilePage } from './ProfilePage';
export function LegalPage() {
  const { kind } = useParams(); const page = legalDocuments[kind as keyof typeof legalDocuments];
  if (!page) return <div className="c-empty">Documento no encontrado. <Link to="/">Volver</Link></div>;
  return <article className="c-legal c-section"><p className="c-eyebrow">TRANSPARENCIA · VERSIÓN {TERMS_VERSION}</p><h1>{page.title}</h1><p className="c-lead">{page.intro}</p><div className="c-panel c-operator"><strong>Responsable: {operator.name || 'pendiente de identificación'}</strong><p>{operator.kind} · iniciativa gratuita con orientación sin fines de lucro</p><p>País de operación: {operator.country || 'pendiente'}</p><p>Contacto: {operator.email ? <a href={`mailto:${operator.email}`}>{operator.email}</a> : 'pendiente de configurar'}</p>{!legalReady ? <p className="c-error">Documento en preparación. El registro en la comunidad requiere completar la identificación del responsable.</p> : null}</div>
    {page.sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}<p className="c-small">Proveedores: <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noreferrer">Firebase{hostingProvider === 'firebase' ? ' · Hosting y servicios de la comunidad' : ''}</a>{hostingProvider === 'vercel' ? <> · <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noreferrer">Vercel · alojamiento web</a></> : null}.</p></article>;
}
export function AboutPage() {
  return <article className="c-section c-legal"><p className="c-eyebrow">FÚTBOL COMO PUNTO DE ENCUENTRO</p><h1>Una cancha<br />sin fronteras.</h1><p className="c-lead">LaCantera busca que organizarse, jugar y mostrar el propio recorrido deportivo sea accesible para todos.</p><section><h2>Una iniciativa con propósito</h2><p>El proyecto nace con vocación sin ánimo de lucro. Su núcleo gratuito permite organizar encuentros, compartir contenido y desarrollar una identidad deportiva, desde un grupo de amigos hasta un club profesional. Esta vocación no implica que exista ya una asociación registrada o una acreditación benéfica.</p></section><section><h2>Patrocinio que abre oportunidades</h2><p>Buscamos aliados que financien infraestructura, comunidad y acceso al deporte. Los acuerdos deberán identificar al patrocinador, sus aportaciones y el uso de los recursos. La verificación y las decisiones de moderación mantendrán su independencia.</p></section><section><h2>Una expansión trazable</h2><p>La hoja de ruta parte de encuentros y contenido, sigue con herramientas para organizadores y tutela de menores, y avanza hacia alianzas locales. El whitepaper y el plan del proyecto documentan los objetivos, los hitos y los criterios de lanzamiento.</p><div className="c-actions"><a className="c-button secondary" href={`${import.meta.env.BASE_URL}Cantera-Whitepaper.pdf`} download="Cantera-Whitepaper.pdf">Descargar whitepaper PDF <ArrowUpRight size={18} /></a><a href={`${import.meta.env.BASE_URL}whitepaper.md`} download="Cantera-Whitepaper.md">Texto editable</a></div></section>{operator.email ? <a className="c-button" href={`mailto:${operator.email}?subject=Colaborar%20con%20LaCantera`}>Proponer una colaboración <ArrowUpRight size={18} /></a> : <p className="c-small">El contacto de colaboraciones se publicará cuando el responsable complete sus datos.</p>}</article>;
}
export function AdminPage() {
  const api = useCommunity(); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const [accountId, setAccountId] = useState(''); const [reason, setReason] = useState('');
  const run = async (id: string, work: () => Promise<void>, message = '') => { setBusy(id); setError(''); setSuccess(''); try { await work(); setSuccess(message); } catch (err) { setError(friendlyError(err)); } finally { setBusy(''); } };
  if (!api.isAdmin) return <div className="c-empty"><ShieldCheck /><h1>Administración</h1><p>Identifícate con la cuenta autorizada del responsable. El acceso con Google por sí solo no concede permisos.</p><button className="c-button" disabled={Boolean(busy)} onClick={() => void run('login', api.loginAdmin)}>Identificar administrador</button>{error ? <p className="c-error" role="alert">{error}</p> : null}<p><Link to="/profile">Revisar cuenta</Link></p></div>;
  const loadMore = (kind: 'verification' | 'reports' | 'rights') => api.adminQueueHasMore[kind] ? <button className="c-button secondary" disabled={api.adminQueueLoading[kind]} onClick={() => void run(kind, () => api.loadMoreAdminQueue(kind))}>Cargar más pendientes</button> : null;
  return <section className="c-section c-admin"><p className="c-eyebrow">CONTROL DE LA COMUNIDAD</p><h1>Administración</h1>{error ? <p role="alert" className="c-error">{error}</p> : null}{success ? <p role="status" className="c-success">{success}</p> : null}
    <section className="c-account-section"><h2>Estado del servicio</h2><p>Estado: {api.runtimeConfig.serviceStatus === 'open' ? 'abierto' : api.runtimeConfig.serviceStatus === 'paused' ? 'en mantenimiento' : 'en preparación'}.</p><p className="c-small">La apertura requiere datos legales y la revisión documentada de nube. Las cargas de archivos continúan cerradas.</p><div className="c-actions"><button className="c-button secondary" disabled={Boolean(busy)} onClick={() => { if (window.confirm('¿Pausar la participación? Las solicitudes de derechos y las retiradas propias siguen disponibles.')) void run('pause', () => api.updateRuntimeStatus('paused'), 'Servicio pausado.'); }}>Pausar participación</button><button className="c-button" disabled={Boolean(busy) || !legalReady || import.meta.env.VITE_SERVICE_OPEN !== 'true'} onClick={() => { if (window.confirm('¿Abrir la participación? Debe haberse aprobado el acta de lanzamiento y la prueba entre dos cuentas reales.')) void run('open', () => api.updateRuntimeStatus('open'), 'Servicio abierto.'); }}>Abrir participación</button></div></section>
    <section className="c-account-section"><h2>Verificación</h2>{api.verificationRequests.length === 0 ? <p>No hay solicitudes pendientes cargadas.</p> : api.verificationRequests.map(r => <article className="c-panel c-admin-card" key={r.id}><h3>{r.organization}</h3><p>Solicitante: <Link to={`/people/${r.userId}`}>{r.name}</Link></p><p className="c-prewrap">{r.evidence}</p><div className="c-actions"><button className="c-button" disabled={Boolean(busy)} onClick={() => void run(r.id, () => api.reviewVerification(r.id, true))}>Aprobar</button><button className="c-button secondary" disabled={Boolean(busy)} onClick={() => void run(r.id, () => api.reviewVerification(r.id, false))}>No aprobar</button></div></article>)}{loadMore('verification')}</section>
    <section className="c-account-section"><h2>Denuncias</h2>{api.reports.length === 0 ? <p>No hay denuncias abiertas cargadas.</p> : api.reports.map(r => <article className="c-panel c-admin-card" key={r.id}><p className="c-prewrap">{r.reason}</p><Link to={`/feed?post=${r.postId}${r.commentId ? `&comment=${r.commentId}` : ''}`}>{r.commentId ? 'Revisar comentario en su publicación' : 'Revisar publicación'}</Link><div className="c-actions"><button className="c-button secondary" disabled={Boolean(busy)} onClick={() => void run(r.id, () => api.resolveReport(r.id, false))}>Cerrar sin retirar</button><button className="c-button" disabled={Boolean(busy)} onClick={() => { if (window.confirm(`¿Retirar ${r.commentId ? 'el comentario' : 'la publicación'} denunciado? El contenido se elimina.`)) void run(r.id, () => api.resolveReport(r.id, true)); }}>Retirar contenido</button></div></article>)}{loadMore('reports')}</section>
    <section className="c-account-section"><h2>Derechos y bajas</h2><p className="c-small">Tramita la exportación o supresión y registra el estado. Marcar completada requiere haber realizado y comprobado el procedimiento; este botón no elimina cuentas.</p>{api.adminRightsRequests.length === 0 ? <p>No hay solicitudes pendientes cargadas.</p> : api.adminRightsRequests.map(r => <article className="c-panel c-admin-card" key={r.id}><h3>{r.kind === 'export' ? 'Exportación' : 'Baja y supresión'}</h3><p>Cuenta: {r.userId}</p><p>Estado: {r.status === 'processing' ? 'en tramitación' : 'pendiente'}</p><div className="c-actions"><button className="c-button secondary" disabled={Boolean(busy)} onClick={() => void run(r.id, () => api.reviewRightsRequest(r.id, 'processing'))}>En tramitación</button><button className="c-button" disabled={Boolean(busy)} onClick={() => { if (window.confirm('¿Has tramitado y comprobado esta solicitud? Confirmar sólo registra su finalización.')) void run(r.id, () => api.reviewRightsRequest(r.id, 'completed')); }}>Registrar finalización</button><button className="c-button secondary" disabled={Boolean(busy)} onClick={() => void run(r.id, () => api.reviewRightsRequest(r.id, 'rejected'))}>Requiere revisión</button></div></article>)}{loadMore('rights')}</section>
    <section className="c-account-section"><h2>Moderación de cuentas</h2><form onSubmit={e => { e.preventDefault(); if (window.confirm('¿Suspender la participación de esta cuenta? Conserva el acceso a sus derechos y retiradas.')) void run('suspend', () => api.suspendAccount(accountId.trim(), reason.trim(), true), 'Participación suspendida.'); }}><label>Identificador de la cuenta<input className="c-input" value={accountId} onChange={e => setAccountId(e.target.value)} required maxLength={128} /></label><label>Motivo de la decisión<textarea className="c-input" value={reason} onChange={e => setReason(e.target.value)} required maxLength={500} rows={3} /></label><div className="c-actions"><button className="c-button" disabled={Boolean(busy)}>Suspender participación</button><button type="button" className="c-button secondary" disabled={Boolean(busy) || !accountId.trim() || !reason.trim()} onClick={() => { if (window.confirm('¿Restablecer la participación de esta cuenta?')) void run('restore', () => api.suspendAccount(accountId.trim(), reason.trim(), false), 'Participación restablecida.'); }}>Restablecer participación</button></div></form></section>
  </section>;
}
