export const operator = {
  name: import.meta.env.VITE_OPERATOR_NAME || '',
  email: import.meta.env.VITE_CONTACT_EMAIL || '',
  country: import.meta.env.VITE_OPERATOR_COUNTRY || '',
  kind: 'Persona física',
};
export const legalReady = Boolean(operator.name && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(operator.email) && operator.country);
export const hostingProvider = import.meta.env.VITE_HOSTING_PROVIDER === 'firebase' ? 'firebase' : 'vercel';
export const legalDocuments = {
  terms: {
    title: 'Términos de uso', intro: 'LaCantera es una iniciativa de acceso gratuito que conecta a personas y equipos a través del fútbol. Estos términos describen las condiciones de participación.',
    sections: [
      ['Responsable y ámbito', 'El responsable identificado al inicio de esta página opera LaCantera. El servicio permite crear encuentros, organizar torneos y compartir contenido deportivo. El acceso internacional no convierte a LaCantera en una federación ni certifica el cumplimiento de los requisitos locales de cada evento.'],
      ['Cuenta y edad', 'Esta primera versión admite cuentas de personas mayores de 18 años que tengan capacidad para aceptar estas condiciones en su país. Los representantes de grupos y clubes deben estar autorizados para actuar por ellos. La participación de menores requiere un sistema de tutores y autorizaciones que se habilitará en una fase posterior. No publiques datos identificativos de menores sin autorización válida.'],
      ['Gratuidad y patrocinio', 'Crear perfiles, organizar partidos y torneos y publicar en el feed no tiene cuota de LaCantera. Un campo, transporte, seguro, material o evento de terceros puede tener costes propios: el organizador debe comunicarlos antes de la inscripción. La iniciativa busca patrocinio para sostener el acceso gratuito. El patrocinio se identificará y no compra la verificación, resultados deportivos ni acceso a datos privados.'],
      ['Organizadores y participantes', 'El organizador debe describir con exactitud país, ciudad, lugar, fecha, zona horaria, nivel, aforo y condiciones, disponer de las autorizaciones necesarias y comunicar cambios o cancelaciones. Los participantes deben valorar su aptitud y las condiciones del lugar. LaCantera facilita la coordinación y no presta servicios médicos, arbitraje oficial, seguros ni reserva automáticamente instalaciones.'],
      ['Contenido y derechos', 'Mantienes tus derechos sobre fotos, vídeos y textos. Al publicarlos autorizas a LaCantera a alojarlos, reproducirlos y mostrarlos dentro del servicio para prestar sus funciones, mientras estén publicados. Debes contar con derechos sobre imágenes, música y personas representadas. No se concede a patrocinadores una licencia para explotar tu contenido mediante estos términos.'],
      ['Visibilidad', 'Los perfiles deportivos, las relaciones de seguimiento, las presentaciones de equipos, eventos abiertos, nombres de participantes inscritos y publicaciones son públicos y pueden compartirse por enlace. Los encuentros privados, sus inscripciones, cruces e historial sólo son accesibles para su organización, sus participantes y el administrador. No aparecen en la búsqueda pública, el feed ni los perfiles públicos. Cada código de invitación a un encuentro privado o conexión caduca a los diez minutos, es de un solo uso y puede cancelarse antes de usarse. Quien lo reciba debe acceder con correo verificado y completar su cuenta. Las conexiones aceptadas se consultan desde las cuentas implicadas y pueden retirarse; no conceden acceso a encuentros privados. Las listas de miembros y roles de los equipos sólo las consultan sus miembros; los responsables del equipo revisan las solicitudes de incorporación y administran invitaciones. La declaración de edad y los datos de aceptación de condiciones se guardan separados del perfil deportivo, con acceso de la propia cuenta y el administrador. Las solicitudes de verificación y denuncias se reservan al responsable y, cuando corresponda, a su autor. Evita publicar teléfonos, direcciones personales, documentación de identidad y otros datos que no quieras hacer públicos.'],
      ['Mensajes entre contactos', 'El chat permite intercambiar texto entre dos contactos recíprocos con cuentas completas. Retirar la conexión, bloquear o suspender una cuenta impide nuevas lecturas y envíos. Bloquear retira la conexión de ambas cuentas; desbloquear no la restaura: es necesario aceptar otra invitación válida. Los datos ya recibidos no pueden retirarse del dispositivo de la otra persona. Si volvéis a conectar, los mensajes conservados pueden reaparecer. Cada autor puede retirar sus mensajes. La conversación no utiliza cifrado de extremo a extremo: las reglas del cliente restringen la lectura a sus participantes, mientras el operador puede tratar datos mediante herramientas privilegiadas para atender derechos o incidentes. No hay llamadas, adjuntos, confirmación de lectura ni avisos push o por correo.'],
      ['Convivencia y moderación', 'Se prohíben el acoso, discriminación, amenazas, suplantación, fraude, spam, contenido sexual o violento ilícito y la exposición de datos privados de terceros. Puedes denunciar publicaciones y comentarios, bloquear cuentas en tu experiencia de comunidad o contactar al responsable. El contenido público sigue siendo público: el bloqueo no convierte un perfil en privado. El administrador puede retirar contenido y revisar cuentas para proteger la comunidad. Puedes solicitar revisión de una decisión mediante el correo de contacto.'],
      ['Verificación y logros', 'La verificación es voluntaria y la decide el administrador tras comprobar la representación de una persona, grupo o entidad. No garantiza talento deportivo, solvencia ni legitimidad de todos sus eventos. Un logro publicado o un marcador aportado por un organizador es una declaración de su autor, salvo indicación expresa de una validación independiente.'],
      ['Disponibilidad y responsabilidad', 'El servicio puede requerir mantenimiento y no garantiza disponibilidad ininterrumpida ni resultados de captación o contratación. Se atenderán incidencias por el canal de contacto. Nada en estos términos limita los derechos ni excluye responsabilidades que la ley aplicable no permita limitar.'],
      ['Baja y cambios', 'Puedes retirar tus publicaciones, comentarios e interacciones propias y registrar desde la cuenta una solicitud de exportación o baja y supresión. Estos derechos y retiradas están disponibles sin aceptar nuevas condiciones. El responsable debe tramitar la solicitud; registrarla no elimina automáticamente la cuenta. Se informará de cambios relevantes en estas condiciones y se pedirá una nueva aceptación cuando corresponda. Los derechos de consumidores y las normas imperativas de la jurisdicción aplicable se mantienen.']
    ]
  },
  privacy: {
    title: 'Privacidad', intro: 'Recogemos los datos necesarios para que puedas organizarte y compartir tu actividad deportiva. No vendemos tus datos ni incorporamos publicidad de seguimiento en esta versión.',
    sections: [
      ['Responsable y contacto', 'El responsable y el correo para solicitudes de privacidad aparecen al inicio de esta página. La iniciativa debe identificar a su responsable antes de abrir el registro a clientes.'],
      ['Datos y finalidades', 'Google Authentication facilita la identidad de acceso (identificador, nombre, correo y foto de la cuenta). El perfil público incluye el nombre elegido, descripción, país, ciudad, equipo, posición y nivel. Guardamos eventos, inscripciones, resultados, publicaciones, comentarios y reacciones para prestar el servicio; relaciones públicas de seguimiento para consultar contenido de las cuentas elegidas; solicitudes de verificación, denuncias, bloqueos y decisiones de moderación para revisar identidad y seguridad; equipos, membresías, roles, invitaciones y solicitudes de acceso para coordinar grupos; códigos temporales, contactos recíprocos aceptados y comprobantes de inscripción para gestionar conexiones y encuentros privados; avisos privados de cambios de encuentros y solicitudes de derechos para atender a la cuenta; comprobantes técnicos de entrega para recuperar avisos pendientes; y la declaración de edad, fecha y versión de aceptación de condiciones en el registro privado de cuenta.'],
      ['Bases del tratamiento', 'La gestión de la cuenta, eventos y publicaciones responde a la prestación del servicio solicitado. La prevención de abuso y la moderación persiguen la seguridad de la comunidad; deben evaluarse y documentarse según la jurisdicción aplicable. Los tratamientos opcionales que requieran consentimiento se ofrecerán de forma separada, sin condicionar las funciones gratuitas. No solicitamos consentimiento de marketing ni instalamos analítica publicitaria.'],
      ['Quién puede ver tus datos', 'El contenido deportivo del módulo de comunidad es público, incluyendo nombres de inscritos y las relaciones entre cuentas que se siguen. Los encuentros privados y su calendario e historial sólo los ven su organización, las cuentas inscritas y el administrador. Las conexiones y códigos no se publican en el directorio; cada cuenta consulta sus contactos y los códigos que ha creado. Los avisos privados que ya recibiste pueden seguir en tu bandeja después de abandonar un encuentro; no dan acceso a sus detalles actualizados. Tu correo de acceso, declaración de edad y aceptación de condiciones no forman parte del perfil deportivo público. El registro privado de cuenta sólo puede consultarse desde tu cuenta o por el administrador. Las listas de miembros de los equipos se reservan a sus miembros, y los responsables revisan sus solicitudes de acceso. Las solicitudes de derechos y los avisos internos sólo los consulta su destinatario y, cuando procede, el administrador. El organizador puede consultar comprobantes de envío para recuperar avisos pendientes, sin acceder al estado de lectura del destinatario. Las solicitudes de verificación pueden contener información privada: sólo tú y el administrador accedéis a ellas. No envíes documentos de identidad o datos sensibles por el campo de solicitud. Los patrocinadores no reciben datos personales por defecto.'],
      ['Mensajería privada', 'Conservamos los identificadores de los dos participantes, el texto y la fecha de los mensajes. El historial no se publica en perfiles, feed ni directorio. La aplicación sólo permite leerlo mientras ambas cuentas mantienen la conexión y cumplen los controles de acceso; las herramientas privilegiadas del operador tienen un alcance distinto. La retirada de la conexión o el bloqueo no borra automáticamente el historial. No ofrecemos cifrado de extremo a extremo. Puedes retirar tus mensajes y tramitar una solicitud de datos o supresión por el canal de privacidad. No compartas datos sensibles en el chat.'],
      ['Proveedores y transferencias', `La integración de LaCantera utiliza Firebase de Google para autenticación y base de datos, y ${hostingProvider === 'firebase' ? 'Firebase Hosting' : 'Vercel'} para el alojamiento web. El almacenamiento de fotos y vídeos en Firebase Storage está preparado en el código, pero su activación espera patrocinio y configuración. Los archivos de la prueba local se conservan únicamente en el navegador. Los proveedores tratan datos técnicos necesarios para los servicios utilizados. Las regiones y garantías de transferencias internacionales deben quedar documentadas por el responsable antes del lanzamiento. Consulta las políticas de los proveedores enlazadas más abajo.`],
      ['Conservación', 'Los perfiles y contenido se conservan mientras la cuenta o publicación estén activas. Los códigos dejan de dar acceso a los diez minutos o al usarse o cancelarse; su estado y los comprobantes de inscripción pueden conservarse para evitar reutilizaciones. Caducar no elimina automáticamente el registro. El responsable debe incluir estos registros y las conexiones en la exportación y supresión de la cuenta. Las solicitudes cerradas de verificación y moderación deben revisarse para eliminar información que ya no sea necesaria. Una baja debe incluir la limpieza de archivos, interacciones, copias y registros con los plazos aplicables, salvo conservación exigida por ley. El responsable publicará los plazos operativos definitivos antes de abrir el servicio.'],
      ['Tus derechos', 'Puedes pedir acceso, rectificación, supresión, portabilidad y, cuando proceda, oposición o limitación en el correo de contacto. La cuenta permite registrar solicitudes de exportación y baja; el responsable informa de su tramitación. No necesitas aceptar una nueva versión de las condiciones para ejercer estos derechos. Se verificará tu identidad de forma proporcionada. También puedes reclamar ante la autoridad de protección de datos competente. Puedes retirar un consentimiento opcional sin que ello afecte a los tratamientos anteriores lícitos.'],
      ['Menores y seguridad', 'La cuenta requiere mayoría de edad autodeclarada en esta versión. La incorporación de menores se habilitará con tutela, controles de contacto y políticas locales revisadas. No compartas datos de salud, identificadores oficiales ni ubicaciones personales precisas. Aplicamos controles de acceso y permisos separados para las funciones administrativas; ningún sistema ofrece seguridad absoluta.']
    ]
  },
  cookies: {
    title: 'Cookies y almacenamiento', intro: 'Una comunidad sin seguimiento publicitario. Esta versión no incorpora cookies de marketing, píxeles publicitarios ni analítica de terceros.',
    sections: [
      ['Almacenamiento necesario', 'Firebase Authentication puede conservar la sesión en el almacenamiento del navegador. LaCantera guarda la elección de publicaciones ocultas para atender tus preferencias. La versión instalable conserva exclusivamente el código y los recursos estáticos de la aplicación para poder abrir su interfaz sin conexión. Ese caché no incluye respuestas de Firebase, perfiles, publicaciones ni archivos de usuarios; las acciones en la comunidad requieren conexión. El sitio utiliza conexiones y registros técnicos del proveedor de alojamiento para servir la página y proteger el servicio. Estos usos deben distinguirse de la publicidad o medición opcional.'],
      ['Servicios externos', 'Cuando eliges entrar con Google, se abre el servicio de Google, que puede utilizar sus propias cookies y políticas. La tipografía no carga fuentes de terceros; el feed no incrusta reproductores de plataformas sociales. Las cargas de vídeos y fotografías en la nube permanecen desactivadas hasta confirmar patrocinio y configurar el almacenamiento. En la prueba local, esos archivos se guardan únicamente en IndexedDB de este navegador.'],
      ['Entorno de prueba', 'Sólo en el entorno de desarrollo o prueba activado explícitamente, los perfiles, eventos e interacciones de prueba se guardan en localStorage y los archivos en IndexedDB de este navegador. No se sincronizan con otros usuarios ni se publican en Firebase.'],
      ['Control', 'Puedes cerrar sesión, eliminar las preferencias o borrar los datos de este sitio desde tu navegador. Esto puede eliminar la sesión o los datos locales de prueba; no borra automáticamente el contenido publicado en tu cuenta. Para eso utiliza las funciones de publicación y el canal de privacidad.'],
      ['Cambios futuros', 'Si se incorporan tecnologías opcionales que requieran consentimiento, se bloquearán hasta que puedas aceptar o rechazar de forma clara y modificar después tu elección. La finalidad y los proveedores se informarán antes de activarlas.']
    ]
  }
};
