import React, { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowUpRight, Link2, Plus, ShieldCheck, Users, X } from 'lucide-react';
import { friendlyError, TERMS_VERSION, useCommunity } from './CommunityContext';
import { useTeamDetail, useTeamEvents, useTeams } from './TeamsContext';
import { assertInvite, isTeamManager } from './teamLogic';
import { CountryInput } from './GeographyFields';
import { timeZoneLabel } from './geography';
import type { TeamInput } from './teamTypes';
import './teams.css';
const emptyInput: TeamInput = { name: '', city: '', country: '', description: '', level: 'amateur' };
function TeamForm({ initial = emptyInput, busy, onSave }: { initial?: TeamInput; busy: boolean; onSave(input: TeamInput): void }) {
  const [input, setInput] = useState(initial);
  return <form onSubmit={e => { e.preventDefault(); onSave(input); }}><fieldset disabled={busy} className="c-profile-fields"><label>Nombre del equipo o grupo<input className="c-input" value={input.name} onChange={e => setInput({ ...input, name: e.target.value })} required maxLength={100} /></label><div className="c-form-grid"><label>País<CountryInput value={input.country} onChange={country => setInput({ ...input, country })} required /></label><label>Ciudad<input className="c-input" value={input.city} onChange={e => setInput({ ...input, city: e.target.value })} required maxLength={100} /></label></div><label>Nivel<select className="c-input" value={input.level} onChange={e => setInput({ ...input, level: e.target.value as TeamInput['level'] })}><option value="amateur">Amateur</option><option value="professional">Profesional</option></select></label><label>Presentación<textarea className="c-input" rows={3} value={input.description} onChange={e => setInput({ ...input, description: e.target.value })} maxLength={1000} /></label><p className="c-small">La presentación es pública. La lista de miembros sólo la ve el equipo. No incluyas teléfonos ni datos privados.</p><button className="c-button" disabled={busy}>{busy ? 'Guardando…' : 'Guardar equipo'}</button></fieldset></form>;
}
export default function TeamsPage() {
  const { teamId, inviteId } = useParams(); const { profile, mode } = useCommunity();
  return inviteId ? <InvitationPage key={`${mode}:${inviteId}:${profile?.id || "guest"}`} inviteId={inviteId} /> : teamId ? <TeamPage key={`${teamId}:${mode}:${profile?.id || 'guest'}`} id={teamId} /> : <TeamDirectory key={`${mode}:${profile?.id || 'guest'}`} />;
}
function TeamDirectory() {
  const api = useTeams(); const { profile } = useCommunity(); const navigate = useNavigate(); const [params, setParams] = useSearchParams();
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [city, setCity] = useState(''); const [country, setCountry] = useState('');
  const active = useRef(true);
  useEffect(() => { active.current = true; return () => { active.current = false; }; }, []);
  const dialog = useRef<HTMLDialogElement>(null); const creating = params.get('create') === '1';
  useEffect(() => { if (creating && profile) dialog.current?.showModal(); else dialog.current?.close(); }, [creating, profile]);
  const close = () => { if (busy) return; const next = new URLSearchParams(params); next.delete('create'); setParams(next, { replace: true }); };
  const matches = api.teams.filter(team => (!city || team.city.toLocaleLowerCase().includes(city.trim().toLocaleLowerCase())) && (!country || team.country.toLocaleLowerCase().includes(country.trim().toLocaleLowerCase())));
  return <section className="c-section team-page"><div className="c-section-head"><div><p className="c-eyebrow">TU GENTE, ORGANIZADA</p><h1>Equipos y grupos</h1><p>Amigos, amateurs y clubes. Un lugar para coordinarse.</p></div><Link className="c-button" to={profile ? '/teams?create=1' : '/profile?returnTo=%2Fteams%3Fcreate%3D1'}><Plus size={18} />Crear equipo gratis</Link></div>
    {api.ownTeams.length ? <section><h2>Tus equipos</h2><div className="team-grid">{api.ownTeams.map(team => <Link className="team-card" to={`/teams/${team.id}`} key={team.id}><Users /><h3>{team.name}</h3><p>{team.city}, {team.country}</p><span>{api.myRoles[team.id] === 'owner' ? 'Propietario' : api.myRoles[team.id] === 'manager' ? 'Responsable' : 'Miembro'}{team.status === 'archived' ? ' · Archivado' : ''}</span></Link>)}</div></section> : null}
    <div className="team-discovery-head"><h2>Encuentra tu equipo</h2><p className="c-small">Filtra los equipos cargados. Puedes seguir cargando para ampliar la búsqueda.</p><div className="c-form-grid"><label>País<CountryInput value={country} onChange={setCountry} /></label><label>Ciudad<input className="c-input" value={city} onChange={e => setCity(e.target.value)} placeholder="Cualquier ciudad" /></label></div></div>
    {api.error ? <p className="c-error" role="alert">{api.error}</p> : null}<div className="team-grid">{matches.map(team => <Link className="team-card" to={`/teams/${team.id}`} key={team.id}><span className="team-monogram">{team.name.slice(0, 2).toUpperCase()}</span><h3>{team.name}</h3><p>{team.city}, {team.country}</p><span>{team.level === 'professional' ? 'Profesional' : 'Amateur'} <ArrowUpRight size={16} /></span></Link>)}</div>{!matches.length ? <div className="c-empty"><Users /><h3>{api.loading ? 'Cargando equipos…' : 'Reúne a tu gente'}</h3><p>{api.hasMore ? 'No hay coincidencias entre los equipos cargados.' : 'No hay equipos que coincidan con estos filtros.'}</p></div> : null}{api.hasMore ? <button className="c-button secondary" disabled={api.loading} onClick={() => void api.loadMore()}>Cargar más equipos</button> : null}
    <dialog className="team-dialog" ref={dialog} onCancel={e => { e.preventDefault(); close(); }} onClose={() => { if (creating) close(); }} aria-labelledby="team-create-title"><header><h2 id="team-create-title">Crea tu equipo</h2><button aria-label="Cerrar" disabled={busy} onClick={close}><X /></button></header><TeamForm busy={busy} onSave={input => { setBusy(true); setError(''); void api.createTeam(input).then(id => { if (active.current) navigate(`/teams/${id}`); }).catch(err => setError(friendlyError(err))).finally(() => setBusy(false)); }} />{error ? <p className="c-error" role="alert">{error}</p> : null}</dialog>
  </section>;
}
function TeamPage({ id }: { id: string }) {
  const api = useTeams(); const { profile } = useCommunity(); const detail = useTeamDetail(id); const agenda = useTeamEvents(id); const { team, role } = detail; const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [edit, setEdit] = useState(false); const [inviteLink, setInviteLink] = useState('');
  const run = async (name: string, fn: () => Promise<void>, message = '') => { setBusy(name); setError(''); setSuccess(''); try { await fn(); if (message) setSuccess(message); } catch (err) { setError(friendlyError(err)); } finally { setBusy(''); } };
  if (detail.loading) return <div className="c-empty" role="status">Cargando equipo…</div>;
  if (!team) return <div className="c-empty"><h1>Equipo no disponible</h1><p>{detail.error || 'El enlace no corresponde a un equipo disponible.'}</p><Link to="/teams">Ver equipos</Link></div>;
  const pending = detail.requests.filter(r => r.status === 'pending'); const myRequest = detail.requests.find(r => r.userId === profile?.id); const manager = isTeamManager(role);
  return <section className="c-section team-page"><Link className="team-back" to="/teams">← Equipos</Link><header className="team-profile-head"><span className="team-monogram">{team.name.slice(0, 2).toUpperCase()}</span><div><p className="c-eyebrow">{team.level === 'professional' ? 'PROFESIONAL' : 'AMATEUR'}{team.status === 'archived' ? ' · ARCHIVADO' : ''}</p><h1>{team.name}</h1><p>{team.city}, {team.country}</p></div></header><p className="c-prewrap">{team.description}</p>
    {error || detail.error ? <p className="c-error" role="alert">{error || detail.error}</p> : null}{success ? <p className="c-success" role="status">{success}</p> : null}
    <div className="c-actions">{manager && team.status === 'active' ? <><Link className="c-button" to={`/play?create=1&team=${id}`}>Organizar encuentro</Link><button className="c-button secondary" disabled={Boolean(busy)} onClick={() => void run('invite', async () => { const token = await api.createInvite(id); const url = `${location.origin}${location.pathname}#/teams/join/${token}`; setInviteLink(url); try { await navigator.clipboard.writeText(url); setSuccess('Enlace copiado. Caduca en 7 días y las incorporaciones requieren aprobación.'); } catch { setSuccess('Comparte el enlace de invitación.'); } })}><Link2 size={17} />Invitar</button></> : null}{role === 'owner' ? <button className="c-button secondary" onClick={() => setEdit(!edit)}>{edit ? 'Cerrar edición' : 'Editar equipo'}</button> : null}{!role && team.status === 'active' ? profile ? <button className="c-button" disabled={Boolean(busy) || myRequest?.status === 'pending'} onClick={() => void run('join', () => api.requestJoin(id), 'Solicitud enviada. Un responsable debe aprobarla.')}>{myRequest?.status === 'pending' ? 'Solicitud pendiente' : 'Solicitar acceso'}</button> : <Link className="c-button" to={`/profile?returnTo=${encodeURIComponent(`/teams/${id}`)}`}>Entrar para solicitar acceso</Link> : null}</div>
    {inviteLink ? <label>Enlace de invitación<input className="c-input" readOnly value={inviteLink} onFocus={e => e.target.select()} /></label> : null}{edit && role === 'owner' ? <div className="c-panel"><TeamForm initial={team} busy={Boolean(busy)} onSave={input => void run('edit', async () => { await api.updateTeam(id, input); setEdit(false); }, 'Equipo actualizado.')} /></div> : null}
    {manager && pending.length ? <section className="team-section"><h2>Solicitudes ({pending.length})</h2>{pending.map(request => <article className="team-member" key={request.id}><div><Link to={`/people/${request.userId}`}>{request.name}</Link><small>Solicita incorporarse</small></div><div><button className="c-button" disabled={Boolean(busy)} onClick={() => void run(request.id, () => api.reviewJoin(id, request.userId, true), 'Nuevo miembro aprobado.')}>Aprobar</button><button className="c-button secondary" disabled={Boolean(busy)} onClick={() => void run(request.id, () => api.reviewJoin(id, request.userId, false), 'Solicitud no aprobada.')}>Rechazar</button></div></article>)}</section> : null}
    {role ? <section className="team-section"><h2>Miembros ({detail.members.length})</h2><p className="c-small">Esta lista sólo está disponible para los miembros del equipo.</p>{detail.members.map(member => <article className="team-member" key={member.id}><div><Link to={`/people/${member.userId}`}>{member.name}</Link><small>{member.role === 'owner' ? 'Propietario' : member.role === 'manager' ? 'Responsable' : 'Miembro'}</small></div>{role === 'owner' && member.userId !== profile?.id ? <div><button className="c-button secondary" disabled={Boolean(busy)} onClick={() => void run(member.id, () => api.changeRole(id, member.userId, member.role === 'manager' ? 'member' : 'manager'))}>{member.role === 'manager' ? 'Quitar rol' : 'Hacer responsable'}</button><details><summary>Más opciones</summary><button disabled={Boolean(busy)} onClick={() => { if (window.confirm(`¿Transferir el equipo a ${member.name}? Pasarás a ser responsable y perderás el control de propiedad.`)) void run(member.id, () => api.transferOwnership(id, member.userId), 'Propiedad transferida.'); }}>Transferir equipo</button><button disabled={Boolean(busy)} onClick={() => { if (window.confirm(`¿Retirar a ${member.name} del equipo?`)) void run(member.id, () => api.removeMember(id, member.userId)); }}>Retirar miembro</button></details></div> : null}</article>)}</section> : <p className="c-small">Los miembros y los roles del equipo se muestran después de la incorporación.</p>}
    <section className="team-section" aria-labelledby="team-agenda-title"><div className="c-section-head"><h2 id="team-agenda-title">Encuentros del equipo</h2>{agenda.status !== 'unavailable' && <button className="c-button secondary" disabled={agenda.loading} onClick={() => void agenda.refresh()}>Actualizar agenda</button>}</div>{agenda.loading && <p className="c-small" role="status">{agenda.events.length ? 'Cargando más encuentros…' : 'Cargando agenda del equipo…'}</p>}{agenda.error && <div><p className="c-error" role="alert">{agenda.error}</p><button className="c-button secondary" disabled={agenda.loading} onClick={() => void agenda.loadMore()}>Volver a intentar</button></div>}{agenda.status === 'unavailable' && <p className="c-small">Esta agenda estará disponible cuando el servicio esté abierto.</p>}{agenda.fromCache && <p className="c-small" role="status">La agenda guardada en este dispositivo puede estar incompleta. Actualiza cuando tengas conexión.</p>}{agenda.invalidCount > 0 && <p className="c-small" role="status">{agenda.invalidCount === 1 ? 'Hay un encuentro que necesita revisión y no se puede mostrar.' : `Hay ${agenda.invalidCount} encuentros que necesitan revisión y no se pueden mostrar.`}</p>}{agenda.events.length > 0 && <div className="c-upcoming">{agenda.events.map(event => <Link className="c-upcoming-card" to={`/play/${event.id}`} key={event.id}><h3>{event.title}</h3><p><time dateTime={event.startAt}>{new Intl.DateTimeFormat('es', { dateStyle: 'medium', timeStyle: 'short', timeZone: event.timeZone }).format(new Date(event.startAt))}</time> · {timeZoneLabel(event.timeZone, event.startAt)}</p><p>{event.city}, {event.country} · {event.venue}</p><span>{event.status === 'completed' ? 'Celebrado' : event.status === 'cancelled' ? 'Cancelado' : event.status === 'closed' ? 'Inscripción cerrada' : Date.parse(event.startAt) < Date.now() ? 'Fecha pasada' : 'Inscripción abierta'}</span></Link>)}</div>}{agenda.status === 'ready' && !agenda.events.length && !agenda.fromCache && !agenda.invalidCount && <p>No hay encuentros publicados para este equipo.</p>}{agenda.hasMore && !agenda.error && <button className="c-button secondary" disabled={agenda.loading} onClick={() => void agenda.loadMore()}>{agenda.loading ? 'Cargando…' : 'Cargar más encuentros del equipo'}</button>}</section>
    {manager ? <section className="team-section"><h2>Invitaciones</h2><p className="c-small">Un enlace permite solicitar acceso. El responsable revisa cada solicitud.</p>{detail.invites.filter(i => !i.revoked && Date.parse(i.expiresAt) > Date.now()).map(invite => <article className="team-member" key={invite.id}><div><small>Caduca {new Intl.DateTimeFormat('es', { dateStyle: 'medium' }).format(new Date(invite.expiresAt))}</small><button onClick={() => setInviteLink(`${location.origin}${location.pathname}#/teams/join/${invite.id}`)}>Mostrar enlace</button></div><button className="c-button secondary" disabled={Boolean(busy)} onClick={() => void run(invite.id, () => api.revokeInvite(invite.id), 'Enlace revocado.')}>Revocar</button></article>)}</section> : null}
    {role ? <section className="team-section team-settings"><h2>Gestión</h2>{role === 'owner' ? <><p>Antes de salir, transfiere el equipo a uno de sus miembros. Archivar cierra nuevas incorporaciones y conserva su historial.</p><button className="c-button secondary" disabled={Boolean(busy) || team.status === 'archived'} onClick={() => { if (window.confirm('¿Archivar el equipo? Sus encuentros conservan sus condiciones y deben cancelarse por separado si corresponde.')) void run('archive', () => api.archiveTeam(id), 'Equipo archivado.'); }}>Archivar equipo</button></> : <button className="c-button secondary" disabled={Boolean(busy)} onClick={() => { if (window.confirm('¿Salir del equipo? Tus inscripciones a encuentros se gestionan por separado.')) void run('leave', () => api.leaveTeam(id), 'Has salido del equipo.'); }}>Salir del equipo</button>}</section> : null}
  </section>;
}
function InvitationPage({ inviteId }: { inviteId: string }) {
  const api = useTeams(); const { profile, mode } = useCommunity(); const [state, setState] = useState<{ id: string; name: string } | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; setLoading(true); setError(''); setState(null); setSent(false); if (!profile) { setLoading(false); return; } void (async () => { const invite = await api.getInvite(inviteId); const team = invite ? await api.getTeam(invite.teamId) : null; assertInvite(invite, team); if (active && team) setState({ id: team.id, name: team.name }); })().catch(err => { if (active) setError(friendlyError(err)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [inviteId, profile?.id, mode]);
  if (!profile) return <section className="c-empty"><Users /><h1>Te han invitado a un equipo</h1><p>Entra para consultar la invitación y confirmar tu solicitud.</p><Link className="c-button" to={`/profile?returnTo=${encodeURIComponent(`/teams/join/${inviteId}`)}`}>Continuar</Link></section>;
  return <section className="c-empty"><ShieldCheck /><h1>{loading ? 'Consultando invitación…' : state ? state.name : 'Invitación no disponible'}</h1>{error ? <p className="c-error" role="alert">{error}</p> : null}{state ? <><p>El enlace no te incorpora automáticamente. Un responsable del equipo revisará tu solicitud.</p>{profile.acceptedTermsVersion !== TERMS_VERSION || !profile.adultConfirmed ? <Link className="c-button" to={`/profile?returnTo=${encodeURIComponent(`/teams/join/${inviteId}`)}`}>Completar perfil</Link> : sent || api.myRoles[state.id] ? <Link className="c-button secondary" to={`/teams/${state.id}`}>{sent ? 'Solicitud enviada · ver equipo' : 'Ya eres miembro · ver equipo'}</Link> : <button className="c-button" disabled={busy} onClick={() => { setBusy(true); void api.requestJoin(state.id, inviteId).then(() => setSent(true)).catch(err => setError(friendlyError(err))).finally(() => setBusy(false)); }}>Solicitar incorporación</button>}</> : <Link to="/teams">Explorar equipos</Link>}</section>;
}
